#!/usr/bin/env python3
"""Deterministically generate modular BLACK BEACON lighthouse OBJ source meshes.

The meshes are authored in Unreal centimetres.  The assembly origin is at the
foot of the tower; the lantern optical pivot is at Z=1980 cm.  No gameplay
collision is generated by this tool.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass
from pathlib import Path


OUT = Path(__file__).resolve().parents[2] / "Lighthouse" / "SourceMeshes"
RNG = random.Random(240924)


@dataclass
class Mesh:
    name: str

    def __post_init__(self):
        self.vertices: list[tuple[float, float, float]] = []
        self.uvs: list[tuple[float, float]] = []
        self.faces: list[tuple[str, tuple[int, ...]]] = []

    def v(self, p, uv=None):
        self.vertices.append(tuple(float(x) for x in p))
        self.uvs.append(tuple(float(x) for x in (uv if uv is not None else (p[0] / 1000.0, p[2] / 1000.0))))
        return len(self.vertices)

    def face(self, material, *ids):
        self.faces.append((material, tuple(ids)))

    def quad(self, material, a, b, c, d):
        self.face(material, a, b, c)
        self.face(material, a, c, d)

    def box(self, center, size, material, yaw=0.0):
        x, y, z = center
        sx, sy, sz = (v * 0.5 for v in size)
        angle = math.radians(yaw)
        ca, sa = math.cos(angle), math.sin(angle)
        points = []
        for dz in (-sz, sz):
            for dy in (-sy, sy):
                for dx in (-sx, sx):
                    points.append((x + dx * ca - dy * sa, y + dx * sa + dy * ca, z + dz))
        # Each face receives its own UV island so narrow trim and tall pilasters
        # do not inherit a tiny shared-vertex projection and stretch the paint.
        for a, b, c, d in ((0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1),
                           (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)):
            face_ids = []
            for index in (a, b, c, d):
                px, py, pz = points[index]
                if abs(points[a][2] - points[b][2]) < 1e-4:
                    uv = ((px - x) / 200.0, (py - y) / 200.0)
                elif abs(points[a][0] - points[b][0]) < 1e-4:
                    uv = ((py - y) / 200.0, (pz - z) / 200.0)
                else:
                    uv = ((px - x) / 200.0, (pz - z) / 200.0)
                face_ids.append(self.v((px, py, pz), uv))
            self.quad(material, *face_ids)

    def cylinder(self, center, radius, height, material, sides=32,
                 top_radius=None, bottom_radius=None, start=0.0):
        x, y, z = center
        rb = radius if bottom_radius is None else bottom_radius
        rt = radius if top_radius is None else top_radius
        lower, upper = [], []
        for i in range(sides):
            a = math.radians(start) + math.tau * i / sides
            lower.append(self.v((x + math.cos(a) * rb, y + math.sin(a) * rb, z - height * 0.5)))
            upper.append(self.v((x + math.cos(a) * rt, y + math.sin(a) * rt, z + height * 0.5)))
        for i in range(sides):
            j = (i + 1) % sides
            self.quad(material, lower[i], lower[j], upper[j], upper[i])
        self.face(material, *reversed(lower))
        self.face(material, *upper)

    def torus(self, z, major, minor, material, sides=64, rings=8):
        grid = []
        for i in range(sides):
            a = math.tau * i / sides
            row = []
            for j in range(rings):
                b = math.tau * j / rings
                r = major + minor * math.cos(b)
                row.append(self.v((math.cos(a) * r, math.sin(a) * r, z + minor * math.sin(b))))
            grid.append(row)
        for i in range(sides):
            ni = (i + 1) % sides
            for j in range(rings):
                nj = (j + 1) % rings
                self.quad(material, grid[i][j], grid[ni][j], grid[ni][nj], grid[i][nj])

    def beam(self, start, end, width, material, cross="square"):
        sx, sy, sz = start
        ex, ey, ez = end
        dx, dy = ex - sx, ey - sy
        length = math.hypot(dx, dy)
        angle = math.degrees(math.atan2(dy, dx))
        self.box(((sx + ex) / 2, (sy + ey) / 2, (sz + ez) / 2),
                 (length, width, max(width, math.hypot(ez - sz, width))), material, angle)

    def write(self, folder: Path):
        folder.mkdir(parents=True, exist_ok=True)
        path = folder / f"{self.name}.obj"
        with path.open("w", encoding="ascii") as f:
            f.write(f"mtllib {self.name}.mtl\no {self.name}\n")
            for x, y, z in self.vertices:
                f.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
            # The Interchange OBJ translator expects a UV index for every vertex.
            # These deterministic planar coordinates are sufficient for the
            # non-textured imported material fallbacks; authored UVs can replace them.
            for u, v in self.uvs:
                f.write(f"vt {u:.6f} {v:.6f}\n")
            active = None
            for material, ids in self.faces:
                if material != active:
                    f.write(f"usemtl {material}\n")
                    active = material
                f.write("f " + " ".join(f"{index}/{index}" for index in ids) + "\n")
        (folder / f"{self.name}.mtl").write_text(
            "newmtl TowerPaint\nKd 0.72 0.75 0.78\nKs 0.12 0.12 0.12\nNs 34\n"
            "newmtl DarkIron\nKd 0.055 0.072 0.082\nKs 0.12 0.12 0.12\nNs 28\n"
            "newmtl WarmBrass\nKd 0.38 0.20 0.065\nKs 0.32 0.27 0.18\nNs 48\n"
            "newmtl LanternGlass\nKd 0.06 0.10 0.12\nKs 0.18 0.18 0.18\nNs 48\n"
            "newmtl AgedWood\nKd 0.15 0.095 0.060\nKs 0.08 0.08 0.08\nNs 18\n"
            "newmtl WetRock\nKd 0.065 0.078 0.080\nKs 0.10 0.10 0.10\nNs 22\n",
            encoding="ascii")
        print(f"{path}: {len(self.vertices)} vertices, {len(self.faces)} triangles")


def tower_shell():
    m = Mesh("SM_BB_LH_TowerShell")
    n = 48
    levels = [(0, 302), (70, 300), (520, 276), (1040, 244), (1460, 218), (1560, 212)]
    rings = []
    for z, r in levels:
        ring = []
        for i in range(n + 1):
            a = math.tau * i / n
            # One UV tile spans about two metres in both axes. A single 0..1 U
            # around the full 19 m circumference caused obvious horizontal stretch.
            ring.append(m.v((math.cos(a) * r, math.sin(a) * r, z),
                            (i / n * math.tau * 250.0 / 200.0, z / 200.0)))
        rings.append(ring)
    for k in range(len(rings) - 1):
        for i in range(n):
            j = i + 1
            m.quad("TowerPaint", rings[k][i], rings[k][j], rings[k + 1][j], rings[k + 1][i])
    # A thin, inward-facing lining keeps the stairwell visually enclosed while
    # the gameplay stair actors remain independent and collision-authoritative.
    inner_rings = []
    for z, radius in levels:
        ring = []
        for i in range(n + 1):
            a = math.tau * i / n
            ring.append(m.v((math.cos(a) * (radius - 20), math.sin(a) * (radius - 20), z),
                            (i / n * math.tau * 230.0 / 200.0, z / 200.0)))
        inner_rings.append(ring)
    for k in range(len(inner_rings) - 1):
        for i in range(n):
            j = i + 1
            m.quad("TowerPaint", inner_rings[k][j], inner_rings[k][i],
                   inner_rings[k + 1][i], inner_rings[k + 1][j])
    # Raised masonry pilasters and restrained ring courses break the plain cylinder silhouette.
    for i in range(16):
        a = math.tau * i / 16
        zmid = 790
        radius = 252
        m.box((math.cos(a) * radius, math.sin(a) * radius, zmid), (25, 13, 1480), "TowerPaint",
              math.degrees(a) + 90)
    for z, r in ((68, 300), (514, 276), (1034, 244), (1452, 219), (1550, 224)):
        m.cylinder((0, 0, z), r + 4, 18, "TowerPaint", 48, top_radius=r - 1, bottom_radius=r + 1)
        m.torus(z + 12, r + 1, 5, "DarkIron", 48, 6)
    # Deep-set narrow windows, aged frames and stone drip ledges.
    for floor, z in enumerate((260, 770, 1275)):
        for index in range(4):
            a = math.radians(18 + index * 90 + floor * 34)
            r = 302 - z * (90 / 1560)
            x, y = math.cos(a), math.sin(a)
            m.box((x * (r + 1), y * (r + 1), z), (58, 16, 150), "LanternGlass",
                  math.degrees(a) + 90)
            for side in (-1, 1):
                tang = side * 36
                m.box((x * (r + 8) - y * tang, y * (r + 8) + x * tang, z),
                      (12, 18, 174), "TowerPaint", math.degrees(a) + 90)
            m.box((x * (r + 11), y * (r + 11), z), (78, 28, 12), "TowerPaint",
                  math.degrees(a) + 90)
            m.box((x * (r + 11), y * (r + 11), z - 88), (78, 28, 16), "TowerPaint",
                  math.degrees(a) + 90)
    return m


def gallery():
    m = Mesh("SM_BB_LH_Gallery")
    m.cylinder((0, 0, 1545), 422, 38, "DarkIron", 64, top_radius=420, bottom_radius=424)
    m.torus(1567, 421, 8, "DarkIron")
    # Outer guardrail and support brackets. Rails are broken into eight readable sides.
    for z in (1590, 1695, 1740):
        m.cylinder((0, 0, z), 424 if z < 1700 else 419, 9, "DarkIron", 64,
                   top_radius=424 if z < 1700 else 419, bottom_radius=424 if z < 1700 else 419)
    for i in range(32):
        a = math.tau * i / 32
        x, y = math.cos(a), math.sin(a)
        m.cylinder((x * 423, y * 423, 1665), 5, 150, "DarkIron", 8)
        if i % 4 == 0:
            m.beam((x * 325, y * 325, 1525), (x * 421, y * 421, 1570), 17, "DarkIron")
            m.cylinder((x * 423, y * 423, 1747), 12, 22, "WarmBrass", 10)
    # Maintenance ladder follows the tapered outside wall; existing stairs remain authoritative.
    for y in (-54, 54):
        m.box((244, y, 1060), (12, 12, 730), "DarkIron")
    for z in range(730, 1411, 68):
        m.box((244, 0, z), (15, 118, 12), "DarkIron")
    return m


def lantern_room():
    m = Mesh("SM_BB_LH_LanternRoom")
    # Optical pivot origin is exactly the gameplay beam component origin (tower-relative Z 1980).
    m.cylinder((0, 0, -132), 184, 42, "DarkIron", 48)
    m.cylinder((0, 0, -104), 164, 18, "WarmBrass", 48)
    m.cylinder((0, 0, 105), 177, 34, "DarkIron", 48, top_radius=187, bottom_radius=167)
    m.torus(-82, 168, 9, "WarmBrass")
    m.torus(91, 179, 7, "WarmBrass")
    for i in range(8):
        a = math.tau * i / 8
        x, y = math.cos(a), math.sin(a)
        m.box((x * 150, y * 150, 0), (16, 16, 178), "DarkIron", math.degrees(a) + 90)
        # Layered Fresnel rings flank the real, powered beam lens at (0,0,0).
        m.torus(-52 + i * 15, 59 + i * 1.4, 3.5, "WarmBrass", 48, 6)
    # Radial optical cage and restrained dark glass panes.
    for i in range(8):
        a = math.tau * (i + 0.5) / 8
        normal = (math.cos(a), math.sin(a))
        tangent = (-normal[1], normal[0])
        px, py = normal[0] * 144, normal[1] * 144
        # The original controller keeps its eight live glass panels and their
        # tested on/off state; only the new optical cage is modeled here.
        m.box((px + tangent[0] * 30, py + tangent[1] * 30, 0),
              (6, 10, 184), "DarkIron", math.degrees(a) + 90)
        m.box((px - tangent[0] * 30, py - tangent[1] * 30, 0),
              (6, 10, 184), "DarkIron", math.degrees(a) + 90)
    # Eight-piece raised lead / zinc domed roof with a heavy drip-edge and finial.
    m.cylinder((0, 0, 131), 195, 24, "DarkIron", 48)
    for step, (z, r) in enumerate(((148, 184), (174, 164), (198, 128), (216, 82), (228, 38))):
        m.cylinder((0, 0, z), r, 30, "DarkIron", 32, top_radius=max(r - 20, 6), bottom_radius=r + 18)
        if step < 4:
            m.torus(z + 13, r - 1, 3, "WarmBrass", 40, 5)
    m.cylinder((0, 0, 252), 22, 28, "WarmBrass", 16, top_radius=12, bottom_radius=22)
    m.cylinder((0, 0, 282), 4, 42, "DarkIron", 10)
    return m


def annex_details():
    m = Mesh("SM_BB_LH_AnnexDetails")
    # Local building centre, fitted over the existing 6.3 x 8.3 m traversable shell.
    # The actual west doorway remains open and the generator/collision stays in its existing place.
    for x in (-150, 150):
        m.box((x, 0, 140), (28, 800, 280), "TowerPaint")
    for y in (-210, 210):
        m.box((0, y, 140), (300, 28, 280), "TowerPaint")
    # Aged open door surround at west wall, with visible hinged leaf swung clear of the entry.
    for y in (-66, 66):
        m.box((-165, y, 112), (28, 22, 228), "DarkIron")
    m.box((-165, 0, 232), (34, 154, 20), "DarkIron")
    m.box((-166, -122, 110), (16, 112, 216), "AgedWood", -38)
    m.cylinder((-151, -164, 105), 7, 16, "WarmBrass", 12)
    # Lead/zinc roof standing seam panels and rain gutters, matching the existing gable footprint.
    for x in range(-210, 211, 42):
        ridge_z = 340 - abs(x) * 0.14
        m.box((x, 0, ridge_z), (8, 846, 10), "DarkIron")
    m.box((0, -418, 301), (492, 22, 16), "DarkIron")
    m.box((0, 418, 301), (492, 22, 16), "DarkIron")
    m.box((0, 0, 365), (18, 846, 12), "DarkIron")
    # Warm, recessed window surrounds on the three visible walls.
    windows = ((150, -230, 176, 52, 100, 0), (150, 230, 176, 52, 100, 0),
               (0, 210, 176, 90, 104, 90), (115, -210, 176, 84, 104, 0))
    for x, y, z, w, h, yaw in windows:
        m.box((x * 1.04, y * 1.04, z), (w, 13, h), "LanternGlass", yaw)
        for side in (-1, 1):
            m.box((x * 1.06 + side * (w / 2 + 8), y * 1.06, z), (12, 24, h + 26), "DarkIron", yaw)
        m.box((x * 1.06, y * 1.06, z + h / 2 + 10), (w + 30, 28, 12), "TowerPaint", yaw)
        m.box((x * 1.06, y * 1.06, z - h / 2 - 12), (w + 30, 38, 16), "TowerPaint", yaw)
    for x in (-144, 144):
        for y in (-204, 204):
            m.box((x, y, 172), (40, 40, 348), "TowerPaint")
    # Chimney stacks / caps and exposed utility pipes.
    for x, y, height in ((-145, -265, 74), (115, 265, 90)):
        m.cylinder((x, y, 340 + height * 0.5), 23, height, "TowerPaint", 8)
        m.cylinder((x, y, 340 + height), 34, 14, "DarkIron", 8)
    for z in range(45, 290, 42):
        m.cylinder((154, -350, z), 5, 10, "DarkIron", 8)
    return m


def rock_plinth():
    m = Mesh("SM_BB_LH_RockPlinth")
    # Faceted irregular basalt blocks ring the tower foot; all faces are visual-only.
    for i in range(40):
        a = math.tau * i / 40 + RNG.uniform(-0.035, 0.035)
        r = RNG.uniform(420, 715)
        cx, cy = math.cos(a) * r, math.sin(a) * r
        rx, ry, rz = RNG.uniform(68, 150), RNG.uniform(52, 128), RNG.uniform(55, 150)
        cx -= math.cos(a) * 35
        cy -= math.sin(a) * 35
        # Low-poly triangulated rock ellipsoid with deterministic coarse variation.
        rings = []
        steps, sides = 5, 9
        for j in range(steps + 1):
            lat = -math.pi / 2 + math.pi * j / steps
            row = []
            for k in range(sides):
                lon = math.tau * k / sides
                variation = RNG.uniform(0.82, 1.18)
                row.append(m.v((cx + rx * math.cos(lat) * math.cos(lon) * variation,
                                cy + ry * math.cos(lat) * math.sin(lon) * variation,
                                -48 + rz * math.sin(lat) * variation)))
            rings.append(row)
        for j in range(steps):
            for k in range(sides):
                nk = (k + 1) % sides
                m.face("WetRock", rings[j][k], rings[j][nk], rings[j + 1][nk])
                m.face("WetRock", rings[j][k], rings[j + 1][nk], rings[j + 1][k])
    return m


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for mesh in (tower_shell(), gallery(), lantern_room(), annex_details(), rock_plinth()):
        mesh.write(OUT)


if __name__ == "__main__":
    main()
