; ============================================================
; BLACK BEACON - DefaultEditor.ini
; ============================================================
; Editor-only project defaults.

[/Script/UnrealEd.EditorEngine]
bShowCompilerOutputOnDraw=False